### ISSUE TITLE
Matrix Q

### ISSUE THREAD

**Issue by CreaperLost** [denniskb/hy475#10]
Can you give us some directions about how to calculate the obs error?

**Comment by grasstr8** [comment]
+1.
We have calculated a relation between the observation and the angle. Given the standard deviation of the angle we have to calculate the standard deviation of the observation (obs error), right or is it something else?

**Comment by denniskb** [comment]
> Can you give us some directions about how to calculate the obs error?

The observation/measurement error is already given to you in the assignment text.

> We have calculated a relation between the observation and the angle

The observation already is an angle. You're thinking of `h`, which relates the state of the rocket to the observation and has nothing to do with finding the observation error.

Reread the following part of the assignment text carefully:

> In contrast to the first assignment there is no need to convert the errors in R and Q to a common unit. (This is handled automatically by the EKF via the matrix H which contains partial derivatives of h. h(mu) converts mu from meters to radians after which the multiplication with K (which has the inverse of H as one of its products) converts it back into meters. Matrix C from the standard Kalman filter merely formatted/re-arranged mu but did not perform any conversions.)
