### ISSUE TITLE
MSE value

### ISSUE THREAD

**Issue by grasstr8** [denniskb/hy475#11]
Hi, I am getting a MSE of ~700, but all the other expected MSE are exactly as you have written. I am having trouble to find what is going wrong, but maybe it is the h(mu). I thought is was trivial and I just had to implement the given diagram, but then h depends on only one component of mu. Could this be the mistake?

**Comment by denniskb** [comment]
After finding `R` "mathematically" I did a *tiny* bit of tuning/adjusting to obtain the lowest MSE I could. I'd suggest you submit your solution.

There are ~3 possible values for `R` that make sense mathematically/intuitively. *I will count all of them as correct*. This also appears to be the [general](https://www.researchgate.net/post/How_should_one_decide_the_initial_state_and_noise_covariance_matrix_in_EKF) [consensus](https://www.researchgate.net/post/How_do_we_determine_noise_covariance_matrices_Q_R): You start with something theoretically sound and then do some tweaking. Apparently there is no exact/"100% correct" way of finding `R`, except perhaps for perfectly modelled, simple examples.
