### ISSUE TITLE
Wiki - Clip space

### ISSUE THREAD

**Issue by Eleanna-ph5068** [denniskb/hy475#21]
Good evening,
When we go from eye space to clip space (y-axis has been flipped), do we know the position of our camera (like in eye space)? If not, how can we determine which grid cells are behind the sensor's frustum? (from this -w <= x(,y,z) < w?)

**Comment by denniskb** [comment]
x is still pointing to the right, y is pointing up now (as is the camera--y flipped, nothing else changed). You only know that the camera is still looking along +y (thus the depth of your points is still defined by their y-coordinates) but you don't know its exact position and you don't care. All coordinates inside the frustum obey `-w <= x,y,z < w` to be visible.

**Comment by denniskb** [comment]
Actually you do know its position, it's `-near -
