### ISSUE TITLE
depth

### ISSUE THREAD

**Issue by mcal1x** [denniskb/hy475#22]
How can we incorporate the depth array with 100 elements to the 3x1 gridWorld vector? It doesn't make sense. Are we interested only in the point on the principal axis of the depth sensor?

**Comment by denniskb** [comment]
`gridWorld` is the (absolute) 2D position of the *center* of grid cell (x,y) in pixels. You can calculate it directly knowing that

- The entire grid/map is 700x700 pixels.
- There are 70x70 grid cells (and thus each grid cell is 10x10 px).
- The top left corner of the grid is (0,0). x extends to the right and y extends downwards.

**Comment by denniskb** [comment]
You're only interested in the pixel of the depth map the grid cell *projects* to, which you will find out once you calculate `xScreen`.
