### ISSUE TITLE
No separation between ghosts, all maps identical

### ISSUE THREAD

**Issue by grasstr8** [denniskb/hy475#26]
Hi,
I have tried different solutions for the third step but I don't get the right results. In all of them there is no separation between the ghosts. In the last implementation I wrote, for every particle, I choose a random value for dir,x,y using the function math.normrnd(mu, std), where mu is this.dir,this.x,this.y and std is 0.07 * abs(deltaDir) for dir and stdx and stdy (which I compute separately) for x,y.
Is this the correct way of thinking, to solve the problem? I have my doubts about stdx,stdy....

Thank you

**Comment by denniskb** [comment]
Forget about the concrete formula for now. You're adding (hopefully) *different* random numbers to the locations of 5 *independent* (?) particles, yet they end up identical. Either

- the randomization isn't big enough. You could plug in a crazy value to test this. Are you getting at least separation from the ground truth bot?
- you don't draw different random numbers, or
- your particles aren't independent for some reason

The fact that you mention `this.x`, `this.y`, etc. makes me think it has something to do with the last point. By implementing step 2 you should've gotten rid of all your `this.x`, `this.y`, ... state variables and only be left with `this.particles` (or however you call your particles array). Look at assign. 3, there is no `this.x` or `this.y` either--the x and y are stored per particle.

**Comment by grasstr8** [comment]
Thank you very much, now my particles are spread out. I followed the implementation of assignment 3. However I am getting exactly the same maps.  Do you know what could be wrong? math.dmf(), passes by reference the grid, so it changes afterwards right?
Also, I added noise only to the angle dir, because the result agrees more with the image you have posted and because if I add noise only to dir also x,y are different for every particle. It seems to me that if I add extra noise to both x,y,  the results are exaggerated. Does this makes sense?

Thank you

**Comment by denniskb** [comment]
De-activate re-sampling for now (simply comment out `this.particles = newParticles;`). Your particles should spread out (and the maps should be different). Is this the case? If, as you say, the maps are the same, perhaps you didn't generate an independent map per particle (initialization)? Once you activate re-sampling again ofc. you want your particles to converge to the ground truth but it's a good check.

Yes the grid (array) is passed by reference. Only primitive types are passed by value in JS, everything else is by reference.

**Comment by grasstr8** [comment]
I was not talking about resampling, I am the third step Randomization, where I also need to have different maps...
