### ISSUE TITLE
Unstable results.

### ISSUE THREAD

**Issue by CreaperLost** [denniskb/hy475#27]
I tried different metrics for depth distance , different N for particles but many times the solution is very bad.
Is this normal due to the randomization or should we get near perfect results like in the final picture all the time?
I am pretty sure the problem is STEP 4 and clipToworld but still asking to better know what to expect as the perfect solution

**Comment by denniskb** [comment]
You should be able to get fairly close, my metric isn't that complex (just took some playing around to find it) and a bunch of students did it as well (with different metrics). Of course you should be sure that your code is bug free before you waste time tuning your weights. A good sanity check is step 3 'randomization': notice that the particles are spread out **and** that each particle's map is *different*.
