### ISSUE TITLE
Question about the bug

### ISSUE THREAD

**Issue by grasstr8** [denniskb/hy475#3]
Hi,

Unfortunately, the RMSE I obtain isn't better after I use the new template. Could it be that there is something wrong with my code? In general the RMSE I obtain is of the order ~2.7px to 2.8px. Does is it need to be lower?

Could you tell us roughly how much the RMSE will decrease after we use the new template? Will it be of the order 0.1px or higher?

Thank you.

**Comment by denniskb** [comment]
About ~0.2px

**Comment by grasstr8** [comment]
Hi,

As far I understood the mistake was in the (3,3) and (4,4) elements of the matrix R, which should be zero but in the first template they were equal to this.errEst*this.errEst. These elements affect the final result when they are multiplied with the elements (1,3),(1,4),(2,3),(2,4) of the C matrix or the corresponding elements when R is multiplied with the transpose of C. Since the observation z is the GPS signal, I thought the interpretation of the C matrix was trivial. This is also based in the implementation of the C matrix when we used the Kalman filter in the form of hand-written equations. 

In general what I am trying to say is the maybe the (3,3) and (4,4) elements of the matrix R don't affect the final result in our case, meaning that we should not observe something different on the RMSE.

Am I wrong about that? Otherwise where was the mistake in the template and where did this 0.2 change come from?

I am sorry if I asked anything that it is not allowed. I am just trying to understand the origin of the change ~0.2px.

Thank you.

**Comment by denniskb** [comment]
Oh but how they do. Yes, the multiplication with `C` eliminates entries (3,3) and (4,4) but `S`, which is the corner stone of our Kalman gain calculation is subject to two update rules `S = A*S*AT + R` and `S = (I-K*C)*S` which do affect entries (1,1) and (2,2). Why don't you `console.log(...)` the matrix `S` in both variants and see for yourself how exactly `S` is affected..
