### ISSUE TITLE
Matrix Q and S

### ISSUE THREAD

**Issue by MichaelM619** [denniskb/hy475#4]
We are given the matrix Q as 2x2 and the matrix S math.zeros(4, 4). Then you are asking for the matrix K, but in the equation i must add matrix Q with matrix S(after multiplying with C+CT) but they are different dimensions. Should my C matrix change the dimension of S to 2x2?

**Comment by denniskb** [comment]
`C` should convert `mu` into the same format as `z` so the two vectors can be subtracted. The `C` that does this will also have the side effect that `C*S*CT` results in a 2x2 matrix so `Q` can be added and `K` calculated.
