### ISSUE TITLE
function h(mu)

### ISSUE THREAD

**Issue by denniskb** [denniskb/hy475#8]
Andrew Zach:

> My question is regarding function h() that relates our state mu=[s, v] to the measurement z. In the 1st assignment the state and the measurement where the same so we defined matrix C so as to preserve the values (is that correct?). In the 2nd assignment we want to relate the s, v to z aka the angle, does that mean that we map the input to a single angle value ? Of course, in that case v is not used to calculate the angle as the problem is geometrical and knowing the distance (200m) and the height s we can find the angle. What am i missing ?

**Comment by denniskb** [comment]
> What am i missing ?

Nothing

**Comment by Eleanna-ph5068** [comment]
I use trigonometry to find h(mu) but I dont need the chain rule at the next step.  I did not use the function g2 in the expression of h(mu). Is this the wrong? I find h(mu) simple enough...

**Comment by denniskb** [comment]
Calculating the derivative of `h(mu)` (with respect to `s`) most certainly requires the chain rule. You can use this [online tool](https://www.derivative-calculator.net/) to double-check your math.

> I did not use the function g2 in the expression of h(mu).

Perhaps you mean you did not use `v` inside `h(mu)`?

**Comment by Eleanna-ph5068** [comment]
I used "this.s" (-> g1). Thank you.
